# -*- coding: utf-8 -*-
"""Project HR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1_vgsfyhxXlR70s7xfKcYFnxJcdcQrc
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/HR_Analytics.csv')

df.head()

print(df.shape)

print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()



#HOW MANY LEFT?
print(df['Attrition'].value_counts())
print(df['Attrition'].value_counts(normalize=True)*100)

#Age vs Attrition
import seaborn as sns
import matplotlib.pyplot as plt
sns.boxplot(x='Attrition', y='Age', data=df)
plt.show()

#Department wise attrition %
print(pd.crosstab(df['Department'],df['Attrition'],normalize='index')*100)

